const
  SimpleHTMLDocument =
    '<!DOCTYPE html>'                                             + //sLineBreak +
    '<html>'                                                      + //sLineBreak +
    '<head>'                                                      + //sLineBreak +
      '<meta charset="utf-8" />'                                  + //sLineBreak +
      '<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com'+
      '/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>'    +
      '<!--[endif]-->'                                              + //sLineBreak +
      '<title>Document Title</title>'                             + //sLineBreak +
      '<meta name="keywords" content="some_keywords keywords" />' + //sLineBreak +
      '<meta name="description" content="description" />'         + //sLineBreak +
      '<link href="style.css" rel="stylesheet">'                  + //sLineBreak +
    '</head>'                                                     + //sLineBreak +
    '<body>'                                                      + //sLineBreak +
      '<div class="wrapper">'                                     + //sLineBreak +
        '<header class="header">'                                 + //sLineBreak +
          '<strong>Header:</strong> Lorem ipsum dolor sit amet,'  +
          'consectetur adipiscing elit. Cras tortor. Praesent '   +
          'dictum, libero ut tempus dictum, neque eros elementum '+
          'mauris, quis mollis arcu velit ac diam. Etiam neque. ' +
          'Quisque nec turpis. Aliquam arcu nulla, dictum et, '   +
          'tempor venenatis. Cum sociis natoque penatibus et '    +
          'magnis dis parturient montes, nascetur ridiculus mus. '+
          'Ut ultricies porttitor purus. Proin non tellus at '    +
          'ligula fringilla tristique. Fusce vehicula quam. '     +
          'Curabitur vel tortor vitae pede imperdiet ultrices. '  +
          'Sed tortor.'                                           + //sLineBreak +
        '</header><!-- .header-->'                                + //sLineBreak +
        '<div class="middle">'                                    + //sLineBreak +
          '<div class="container">'                               + //sLineBreak +
            '<main class="content">'                              + //sLineBreak +
              '<strong>Content:</strong> Sed placerat accumsan '  +
              'ligula. Aliquam felis magna, congue quis, tempus ' +
              'eu, aliquam vitae, ante. Cras neque justo, '       +
              'ultrices at, rhoncus a, facilisis eget, nisl. '    +
              'Quisque vitae pede. Nam et augue. Sed a elit. Ut ' +
              'vel massa. Suspendisse nibh pede, ultrices vitae, '+
              'ultrices nec, mollis non, nibh. In sit amet pede ' +
              'quis leo vulputate hendrerit. Cras laoreet leo et '+
              'justo auctor condimentum. Integer id enim. '       +
              'Suspendisse egestas, dui ac egestas mollis, '      +
              'libero orci hendrerit lacus, et malesuada lorem '  +
              'neque ac libero. Morbi tempor pulvinar pede. '     +
              'Donec vel elit.'                                   + //sLineBreak +
            '</main><!-- .content -->'                            + //sLineBreak +
          '</div><!-- .container-->'                              + //sLineBreak +
          '<aside class="left-sidebar">'                          + //sLineBreak +
            '<strong>Left Sidebar:</strong> Integer velit. '      +
            'Vestibulum nisi nunc, accumsan ut, vehicula sit '    +
            'amet, porta a, mi. Nam nisl tellus, placerat eget, ' +
            'posuere eget, egestas eget, dui. Pellentesque '      +
            'habitant morbi tristique senectus et netus et '      +
            'malesuada fames ac turpis egestas. In elementum '    +
            'urna a eros. Integer iaculis. Maecenas vel elit.'    + //sLineBreak +
          '</aside><!-- .left-sidebar -->'                        + //sLineBreak +
        '</div><!-- .middle-->'                                   + //sLineBreak +
        '<footer class="footer">'                                 + //sLineBreak +
          '<strong>Footer:</strong> Mus elit Morbi mus enim '     +
          'lacus at quis Nam eget morbi. Et semper urna urna non '+
          'at cursus dolor vestibulum neque enim. Tellus '        +
          'interdum at laoreet laoreet lacinia lacinia sed '      +
          'Quisque justo quis. Hendrerit scelerisque lorem elit ' +
          'orci tempor tincidunt enim Phasellus dignissim '       +
          'tincidunt. Nunc vel et Sed nisl Vestibulum odio '      +
          'montes Aliquam volutpat pellentesque. Ut pede '        +
          'sagittis et quis nunc gravida porttitor ligula.'       + //sLineBreak +
        '</footer><!-- .footer -->'                               + //sLineBreak +
      '</div><!-- .wrapper -->'                                   + //sLineBreak +
    '</body>'                                                     + //sLineBreak +
    '</html>';
